### ISSUE TITLE
Percentile change from feature to feature?

### ISSUE THREAD

**Issue by AveryLiu** [ShuaiW/how-to-kaggle#1]
Hi Wang,

I'm doing a competition and found this post very useful. You've mentioned **Percentile change from feature to feature** in a writeup with the link down below (under section **Feature selection round 2**). In your case, this gives tremendous boost in terms of number of features (from 57 to 308). I wonder what this so called **Percentile change from feature to feature** means and how to put it into practice. I've googled it but no appropriate explanation presents.  

Thanks.

[Writeup](https://docs.google.com/document/d/1YrcN60jrYJwDL5F8yyd6_Yj279GSZMNBEOHwTBxwP8c/edit#)

**Comment by jayinai** [comment]
@AveryLiu Glad it helps. So it boils down to tracking one type of interaction among features. There is a code snippet

``` python

def add_percentile_change(dataframe):
  """
  Takes a pandas dataframe and adds percentile change from feature to feature.

  Parameters
  ----------
  dataframe: a dataframe

  Returns
  ----------
  A dataframe with percentile changes added

  """
  col_name = dataframe.columns
  for i in xrange(len(col_name)):
    for j in xrange(len(col_name)):
      new_col = col_name[i] + '_SUBTRACT_' + col_name[j] + '_DIVIDE_' + col_name[i]
      dataframe[new_col] = (dataframe[col_name[i]] - dataframe[col_name[j]]) / dataframe[col_name[i]]

  # above operations generate nan and inf, replace them
  dataframe.replace(np.inf, 999999, inplace=True)
  dataframe.replace(-np.inf, -999999, inplace=True)
  dataframe.replace(np.nan, -1, inplace=True)

  return dataframe
```

Note that this might be slow for high dimensional data (double loop), and might not make sense for your dataset. It's just that adding those boosts my model performance a little bit. 

You can then use feature selection techniques to remove some uninteresting features.

**Comment by AveryLiu** [comment]
Thanks for your kind response, now I know what it is. 

But I still wonder should all the values in each column be normalized before they are percentile changed? Because some values are nominal, ranging from 0 ~ maybe 100000, while others only range from 0~1.

Thanks.
